import streamlit as st
import google.generativeai as genai
from PIL import Image
from fpdf import FPDF
import datetime
import re

# --- PAGE CONFIGURATION ---
st.set_page_config(page_title="BootCheck", layout="wide")

# --- CUSTOM MODERN DESIGN (CSS) ---
st.markdown("""
    <style>
    .main {
        background-color: #fcfcfc;
    }
    h1, h2, h3 {
        color: #111111;
        font-family: 'Inter', -apple-system, sans-serif;
        font-weight: 800;
        letter-spacing: -1px;
    }
    
    #MainMenu {visibility: hidden;}
    footer {visibility: hidden;}
    header {visibility: hidden;}

    [data-testid="stSidebar"] {
        background-color: #ffffff;
        border-right: 1px solid #f0f0f0;
    }

    .stButton>button {
        background-color: #000000;
        color: #ffffff;
        border-radius: 2px;
        border: none;
        padding: 15px 30px;
        font-weight: 500;
        text-transform: uppercase;
        letter-spacing: 1px;
        transition: all 0.2s ease;
        width: 100%;
    }
    .stButton>button:hover {
        background-color: #222222;
        color: #ffffff;
    }

    .stFileUploader {
        border: 1px solid #eeeeee;
        border-radius: 4px;
        padding: 10px;
    }
    </style>
    """, unsafe_allow_html=True)

# --- SYSTEM SETUP ---
API_KEY = "AIzaSyBFVz-AVRfNnXsST50eL_Y82-2x3b49iQk"
genai.configure(api_key=API_KEY)

try:
    available_models = [m.name for m in genai.list_models() if 'generateContent' in m.supported_generation_methods]
    selected_model = next((m for m in available_models if 'flash' in m.lower()), available_models[0])
    engine = genai.GenerativeModel(selected_model)
except Exception:
    st.error("System connection error.")

# --- PDF GENERATOR ---
def create_pdf(report_text, brand, model_name):
    pdf = FPDF()
    pdf.add_page()
    
    # Cleaning special characters
    clean_text = report_text.encode('latin-1', 'ignore').decode('latin-1')
    
    # Layout - Clean & Minimal
    pdf.set_font("Helvetica", "B", 18)
    pdf.cell(0, 15, "BOOTCHECK VERIFICATION REPORT", ln=True)
    pdf.set_font("Helvetica", "", 9)
    pdf.cell(0, 5, f"Issued on: {datetime.date.today()} | Report ID: {datetime.datetime.now().strftime('%Y%m%d%H%M')}", ln=True)
    pdf.line(10, 35, 200, 35)
    
    pdf.ln(15)
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 10, f"PRODUCT: {brand.upper()} {model_name.upper()}", ln=True)
    
    # Logic to detect authenticity status correctly
    status_text = "INSPECTION REQUIRED / HIGH RISK"
    pdf.set_text_color(180, 0, 0) # Red default
    
    positive_keywords = ["LEGIT", "AUTHENTIC", "VERIFIED", "GENUINE"]
    if any(word in clean_text.upper() for word in positive_keywords):
        status_text = "VERIFIED AUTHENTIC"
        pdf.set_text_color(0, 100, 0) # Dark Green
    
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 10, f"STATUS: {status_text}", ln=True)
    
    pdf.set_text_color(0, 0, 0)
    pdf.ln(10)
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(0, 8, "DETAILED ANALYSIS:", ln=True)
    pdf.set_font("Helvetica", "", 9)
    pdf.multi_cell(0, 6, clean_text)
    
    pdf.ln(20)
    pdf.set_font("Helvetica", "I", 7)
    pdf.cell(0, 10, "This digital report is for informational purposes and generated by the BootCheck Engine.", align='L')
    
    return bytes(pdf.output())

# --- UI CONTENT ---
st.title("BootCheck")
st.markdown("##### High-Precision Product Verification")

with st.sidebar:
    st.markdown("### Specifications")
    brand = st.selectbox("Brand", ["Nike", "Adidas", "Puma", "Mizuno", "UA", "New Balance"])
    user_model = st.text_input("Model Name", "Phantom GX Elite")
    tier = st.selectbox("Tier", ["Elite", "Pro", "Academy", "Club"])
    weight = st.number_input("Measured Weight (g)", value=215)
    st.divider()
    st.caption("Engine: 1.5.2 Pro")

st.markdown("### Evidence Upload")
st.caption("Submit high-resolution captures for structural analysis.")

col1, col2 = st.columns(2)
with col1:
    side_img = st.file_uploader("Side Profile", type=['jpg','png','jpeg'])
    sole_img = st.file_uploader("Soleplate", type=['jpg','png','jpeg'])
    tag_img = st.file_uploader("Inner Tag", type=['jpg','png','jpeg'])
with col2:
    heel_img = st.file_uploader("Heel Symmetry", type=['jpg','png','jpeg'])
    stitch_img = st.file_uploader("Construction/Stitching", type=['jpg','png','jpeg'])

if 'report' not in st.session_state:
    st.session_state.report = None

if st.button("RUN VERIFICATION"):
    if side_img and sole_img and tag_img:
        with st.spinner('Analyzing patterns and production markers...'):
            uploaded_list = [side_img, sole_img, tag_img]
            if heel_img: uploaded_list.append(heel_img)
            if stitch_img: uploaded_list.append(stitch_img)
            
            pil_images = [Image.open(i) for i in uploaded_list]
            
            # Explicit instruction for 100-point score
            prompt = f"""
            You are a professional product verifier. Analyze these images of a {brand} {user_model}.
            Weight: {weight}g.
            
            Requirements:
            1. Provide a SCORE strictly between 0 and 100 based on authenticity.
            2. Verdict must be clearly stated as LEGIT or FAKE.
            3. Detailed findings on SKU, texture, and construction.
            
            Structure:
            VERDICT: 
            SCORE: (0-100)
            FINDINGS:
            CONCLUSION:
            """
            try:
                response = engine.generate_content([prompt] + pil_images)
                st.session_state.report = response.text
            except Exception as e:
                st.error(f"Hibaüzenet: {e}")
    else:
        st.error("Upload at least 3 images (Side, Sole, Tag).")

if st.session_state.report:
    st.divider()
    st.subheader("Verification Report")
    st.markdown(st.session_state.report)
    
    try:
        pdf_data = create_pdf(st.session_state.report, brand, user_model)
        st.download_button(
            label="Download Verification Report (PDF)",
            data=pdf_data,
            file_name=f"BootCheck_{user_model.replace(' ', '_')}.pdf",
            mime="application/pdf"
        )
    except Exception as e:
        st.warning(f"Document generation error: {e}")

st.divider()

st.caption("BootCheck Verification Services 2026")
